

theme = "zFx"


[editor]
line-number = "relative"
mouse = true
color-modes = true
#bufferline = "multiple"
cursorline = true
#cursorcolumn = true
bufferline = "always"
#indendent-heuristic = "tree-sitter"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

#cargo xtask themelint dark_plus # replace onedark with <name>,

#"ui.cursor" = { fg = "bg", bg = "fg" }
